YOLOX:
  conf: 0.7
  nms: 0.45
  tsize: 640
  cfg: '../licenseplate_detection/src/OCR/configs/small_satrn.py'
  ckpt: '../licenseplate_detection/src/YOLOX/yolox/YOLOX_outputs/yolox_s/best_ckpt.pth'
  checkpoint: '../licenseplate_detection/src/OCR/checkpoint/small_satrn.pth'
  gpus: '0'